# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x86
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x86)
  game_of_life_config = debug_x86

else ifeq ($(config),debug_x64)
  game_of_life_config = debug_x64

else ifeq ($(config),release_x86)
  game_of_life_config = release_x86

else ifeq ($(config),release_x64)
  game_of_life_config = release_x64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := game-of-life

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

game-of-life:
ifneq (,$(game_of_life_config))
	@echo "==== Building game-of-life ($(game_of_life_config)) ===="
	@${MAKE} --no-print-directory -C . -f game-of-life.make config=$(game_of_life_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f game-of-life.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x86"
	@echo "  debug_x64"
	@echo "  release_x86"
	@echo "  release_x64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   game-of-life"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"